#!/bin/bash
###############################################################################
# BinBuddy Master Bootstrap Orchestrator
# Calls individual bootstrap scripts in correct order
#
# Author: Evyatar Beni
# Email: evyatarbeni@gmail.com
#
# This is the main entry point that generates all ROS 2 packages.
# Each package is generated by its own script for easy maintenance.
###############################################################################

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROS2_WS="$(dirname "$SCRIPT_DIR")/ros2_ws"

GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║     BinBuddy Bootstrap - Generating ROS 2 Workspace     ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""

# Create workspace structure
mkdir -p "$ROS2_WS/src"
cd "$ROS2_WS/src"

# Execute bootstrap scripts in order
echo -e "${BLUE}Starting package generation...${NC}\n"

bash "$SCRIPT_DIR/bootstrap_interfaces.sh" "$ROS2_WS/src"
bash "$SCRIPT_DIR/bootstrap_base_crane.sh" "$ROS2_WS/src"
bash "$SCRIPT_DIR/bootstrap_description.sh" "$ROS2_WS/src"
bash "$SCRIPT_DIR/bootstrap_sensing.sh" "$ROS2_WS/src"
bash "$SCRIPT_DIR/bootstrap_navigation_slam.sh" "$ROS2_WS/src"
bash "$SCRIPT_DIR/bootstrap_teleop_nlp.sh" "$ROS2_WS/src"
bash "$SCRIPT_DIR/bootstrap_bringup.sh" "$ROS2_WS/src"

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║      All ROS 2 Packages Generated Successfully!         ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""
echo "Workspace location: $ROS2_WS"
echo "Ready to build with: cd $ROS2_WS && colcon build"
