<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="binbuddy">

  <!-- Properties -->
  <xacro:property name="wheel_base" value="0.35"/>
  <xacro:property name="wheel_radius" value="0.075"/>
  <xacro:property name="wheel_width" value="0.05"/>
  <xacro:property name="base_length" value="0.5"/>
  <xacro:property name="base_width" value="0.4"/>
  <xacro:property name="base_height" value="0.15"/>
  <xacro:property name="crane_height" value="0.8"/>

  <!-- Materials -->
  <material name="blue">
    <color rgba="0.2 0.2 0.8 1.0"/>
  </material>
  <material name="black">
    <color rgba="0.1 0.1 0.1 1.0"/>
  </material>
  <material name="orange">
    <color rgba="1.0 0.5 0.0 1.0"/>
  </material>
  <material name="red">
    <color rgba="0.8 0.0 0.0 1.0"/>
  </material>

  <!-- Base footprint (on ground) -->
  <link name="base_footprint"/>

  <!-- Base link -->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="15.0"/>
      <inertia ixx="0.5" ixy="0.0" ixz="0.0" 
               iyy="0.5" iyz="0.0" izz="0.5"/>
    </inertial>
  </link>

  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
  </joint>

  <!-- LiDAR -->
  <link name="lidar_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.08"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder radius="0.05" length="0.08"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0" 
               iyy="0.001" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_link"/>
    <origin xyz="0.15 0 ${base_height/2 + 0.08}" rpy="0 0 0"/>
  </joint>

  <!-- USB Camera (front center) -->
  <link name="camera_usb_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 0.08 0.03"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>

  <joint name="camera_usb_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_usb_link"/>
    <origin xyz="0.25 -0.08 ${base_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- USB Camera optical frame -->
  <link name="camera_usb_optical"/>
  <joint name="camera_usb_optical_joint" type="fixed">
    <parent link="camera_usb_link"/>
    <child link="camera_usb_optical"/>
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
  </joint>

  <!-- Pi Camera 1 (front right) -->
  <link name="camera_picam1_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 0.08 0.03"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>

  <joint name="camera_picam1_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_picam1_link"/>
    <origin xyz="0.25 0.08 ${base_height/2}" rpy="0 0 0"/>
  </joint>

  <link name="camera_picam1_optical"/>
  <joint name="camera_picam1_optical_joint" type="fixed">
    <parent link="camera_picam1_link"/>
    <child link="camera_picam1_optical"/>
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
  </joint>

  <!-- Pi Camera 2 (rear center) -->
  <link name="camera_picam2_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 0.08 0.03"/>
      </geometry>
      <material name="black"/>
    </visual>
  </link>

  <joint name="camera_picam2_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_picam2_link"/>
    <origin xyz="-0.25 0 ${base_height/2}" rpy="0 0 ${pi}"/>
  </joint>

  <link name="camera_picam2_optical"/>
  <joint name="camera_picam2_optical_joint" type="fixed">
    <parent link="camera_picam2_link"/>
    <child link="camera_picam2_optical"/>
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
  </joint>

  <!-- Crane base -->
  <link name="crane_base_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.2"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.1 0.2"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="2.0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" 
               iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

  <joint name="crane_base_joint" type="fixed">
    <parent link="base_link"/>
    <child link="crane_base_link"/>
    <origin xyz="-0.15 0 ${base_height/2 + 0.1}" rpy="0 0 0"/>
  </joint>

  <!-- Crane arm (prismatic joint for vertical movement) -->
  <link name="crane_arm_link">
    <visual>
      <origin xyz="0 0 ${crane_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 ${crane_height}"/>
      </geometry>
      <material name="orange"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${crane_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.05 ${crane_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.5"/>
      <inertia ixx="0.05" ixy="0.0" ixz="0.0" 
               iyy="0.05" iyz="0.0" izz="0.001"/>
    </inertial>
  </link>

  <joint name="crane_arm_joint" type="prismatic">
    <parent link="crane_base_link"/>
    <child link="crane_arm_link"/>
    <origin xyz="0 0 0.1" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="0.0" upper="${crane_height}" effort="100.0" velocity="0.2"/>
  </joint>

  <!-- Crane gripper/hook -->
  <link name="crane_gripper_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.15 0.1 0.05"/>
      </geometry>
      <material name="red"/>
    </visual>
  </link>

  <joint name="crane_gripper_joint" type="fixed">
    <parent link="crane_arm_link"/>
    <child link="crane_gripper_link"/>
    <origin xyz="0 0 ${crane_height}" rpy="0 0 0"/>
  </joint>

</robot>
